spring:
  application:
    name: springboot-scheduler

  mail:
    host: smtp.gmail.com
    port: 587
    username: roysubham505@gmail.com
    password: "rnzy pvls izyq jjyp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8088
